apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: "KarpenterNodeRole-norel-eks-cluster-20250227200341046900000005"
  amiSelectorTerms:
    - alias: "al2023@v20250212"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "norel-eks-cluster"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "norel-eks-cluster"
  tags:
    karpenter.sh/discovery: "norel-eks-cluster" 
